spring:
  redis:
    host: 172.16.22.124
    port: 6379
    database: 0
    password: 1qaz2wsx!QAZ@WSX
    # redisson配置
    redisson:
      file: classpath:redisson.yml
  cache:
    type: redis
    redis:
      use-key-prefix: false
