spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 1qaz2wsx!QAZ@WSX
    # redisson配置
    redisson:
      file: classpath:redisson.yml
  cache:
    type: redis
    redis:
      use-key-prefix: false
