server:
  port: 10001

spring:
  profiles:
    include: druid,redis,quartz

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

